# Basic Pandas Operation

In [ ]:
# a import necessary library
import pandas as pd

In [5]:
# b import data.csv
# set user_id as row index
data = pd.read_csv('data/occupation.csv', index_col=0)

In [10]:
# c print the first 25 rows
data.head(25)
# data.iloc[:25]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [12]:
# d print the last 10 rows
data.tail(10)
# data.iloc[-10:]

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [17]:
# e print number of observations
print('Number of observations with len = ', len(data))
print('Number of observations with shape = ', data.shape[0])
print('Number of observations with index = ', data.index.size)

Number of observations with len =  943
Number of observations with shape =  943
Number of observations with index =  943

In [18]:
# f print number of columns
print('Number of columns with len = ', len(data.columns))
print('Number of columns with shape = ', data.shape[1])
print('Number of columns with index = ', data.columns.size)

Number of columns with len =  4
Number of columns with shape =  4
Number of columns with index =  4

In [21]:
# g print the column names
# data.columns
print('Column names = ', data.columns.tolist())

Column names =  ['age', 'gender', 'occupation', 'zip_code']

In [22]:
# h print the index numbers
data.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [25]:
# i print data types of each column
data.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [28]:
# j print occupation column
# data['occupation']
data.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [32]:
# k count number of occupations
print('Number of occupations = ', data.occupation.unique().size)
print('Number of occupations = ', data.occupation.nunique())

Number of occupations =  21
Number of occupations =  21

In [33]:
# l print list of user aged 50 and above
print('Users aged 50 and above:')
print(data[data.age >= 50].index.tolist())

# count number of users aged 50 and above
print('Number of users aged 50 and above = ', data[data.age >= 50].shape[0])

Users aged 50 and above:
[2, 7, 10, 47, 60, 65, 82, 85, 90, 91, 106, 111, 121, 131, 133, 136, 137, 144, 157, 158, 161, 169, 170, 172, 173, 185, 197, 204, 211, 225, 234, 266, 271, 273, 308, 318, 328, 349, 351, 360, 364, 370, 384, 392, 396, 406, 413, 418, 420, 423, 426, 427, 438, 441, 444, 446, 454, 464, 469, 474, 480, 481, 489, 492, 503, 515, 516, 520, 523, 524, 539, 547, 548, 553, 558, 559, 562, 564, 572, 573, 574, 585, 590, 591, 614, 616, 623, 644, 651, 655, 662, 672, 673, 678, 694, 696, 701, 704, 707, 722, 728, 752, 753, 754, 767, 772, 777, 788, 803, 809, 810, 819, 845, 855, 858, 860, 878, 891, 900, 909, 912, 915, 931, 932, 934]
Number of users aged 50 and above =  125

In [34]:
# m print descriptive statistics
print('Descriptive statistics:')
data.describe()

Descriptive statistics:

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [36]:
# n print descriptive statistic for all columns
# set include='all' to include non-numeric columns, otherwise it will only include numeric columns
print('Descriptive statistics for all columns:')
data.describe(include='all')

Descriptive statistics for all columns:

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [38]:
# o print descriptive statistics for occupation column
print('Descriptive statistics for occupation column:')
data.occupation.describe()

Descriptive statistics for occupation column:

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [39]:
# p calculate mean age
mean_age = data.age.mean()
print('Mean age = ', mean_age)

Mean age =  34.05196182396607

In [42]:
# q print age with least occurrences
data.age.value_counts().tail()

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

In [43]:
# r add new salary column with initial value of 0
data['salary'] = 0
data

         age gender     occupation zip_code  salary
user_id
1         24      M     technician    85711       0
2         53      F          other    94043       0
3         23      M         writer    32067       0
4         24      M     technician    43537       0
5         33      F          other    15213       0
...      ...    ...            ...      ...     ...
939       26      F        student    33319       0
940       32      M  administrator    02215       0
941       20      M        student    97229       0
942       48      F      librarian    78209       0
943       22      M        student    77841       0

[943 rows x 5 columns]

In [44]:
# s set salary of each user to 100 multiplied by their age
data['salary'] = data.age * 100
data

         age gender     occupation zip_code  salary
user_id
1         24      M     technician    85711    2400
2         53      F          other    94043    5300
3         23      M         writer    32067    2300
4         24      M     technician    43537    2400
5         33      F          other    15213    3300
...      ...    ...            ...      ...     ...
939       26      F        student    33319    2600
940       32      M  administrator    02215    3200
941       20      M        student    97229    2000
942       48      F      librarian    78209    4800
943       22      M        student    77841    2200

[943 rows x 5 columns]